

NAME					= megaphone
C++/CC					=
C++_FLAGS/CFLAGS		=

#directories
SRC_DIR					= megaphone.cpp
OBJ_DIR					=
INC_DIR					=

#src files
SRC_FILES		=
OBJ_FILES		=


#color
RESET		=	\033[0m
GREEN		=	\033[32m
YELLOW		=	\033[33m
BLUE		=	\033[34m
RED			=	\033[31m
UP			=	\033[A
CUT			=	\033[K


all:

clean:

fclean:

re:

.PHONY: all clean fclean re